In [ ]:
import pickle
import numpy as np

### About libraries
Numpy is a very useful python library. Using [NumPy](http://cs231n.github.io/python-numpy-tutorial/), mathematical and logical operations on arrays can be performed.
<br>The [pickle](https://www.youtube.com/watch?v=2Tw39kZIbhs) module implements a fundamental, but powerful algorithm for serializing and de-serializing a Python object structure.

In [ ]:
## Code to load the array
with open('array.pickle', 'rb') as p:
    arr = pickle.load(p)

### Task 1: Write the code and check the size of the array

In [1]:
## BEGIN CODE
import numpy as np
a=np.array([1,2,3,4,4])
a.size
## END CODE

5

Check that the size of the array (arr) is 1000. Please report in case fo any discrepancy.

### Task 2: Resize the array to a (40x50) matrix

In [7]:
## BEGIN CODE
import numpy as np
l=np.arange(2000).reshape(40,50)
print(l)

## END CODE

[[   0    1    2 ...   47   48   49]
 [  50   51   52 ...   97   98   99]
 [ 100  101  102 ...  147  148  149]
 ...
 [1850 1851 1852 ... 1897 1898 1899]
 [1900 1901 1902 ... 1947 1948 1949]
 [1950 1951 1952 ... 1997 1998 1999]]


### Task 3: Find the transpose of this matrix

In [10]:
## BEGIN CODE
l.transpose()
## END CODE

### Task 3: Find the dot product of the matrices created in Tasks 2 & 3

In [14]:
## BEGIN CODE
c=l.dot(l.transpose())
print(c)
## END CODE

[[    40425    101675    162925 ...   2306675   2367925   2429175]
 [   101675    287925    474175 ...   6992925   7179175   7365425]
 [   162925    474175    785425 ...  11679175  11990425  12301675]
 ...
 [  2306675   6992925  11679175 ... 175697925 180384175 185070425]
 [  2367925   7179175  11990425 ... 180384175 185195425 190006675]
 [  2429175   7365425  12301675 ... 185070425 190006675 194942925]]


### Task 4: Find the row wise sum of the resulting matrix

In [15]:
## BEGIN CODE
c.sum(axis=1)
## END CODE

array([   49392000,   149342000,   249292000,   349242000,   449192000,
         549142000,   649092000,   749042000,   848992000,   948942000,
        1048892000,  1148842000,  1248792000,  1348742000,  1448692000,
        1548642000,  1648592000,  1748542000,  1848492000,  1948442000,
        2048392000, -2146625296, -2046675296, -1946725296, -1846775296,
       -1746825296, -1646875296, -1546925296, -1446975296, -1347025296,
       -1247075296, -1147125296, -1047175296,  -947225296,  -847275296,
        -747325296,  -647375296,  -547425296,  -447475296,  -347525296])

### Task 5: Find the cube root of all elements in the resulting matrix

In [16]:
## BEGIN CODE
print(c**(1/3))
## END CODE

[[ 34.32021577  46.67361008  54.61717627 ... 132.12818509 133.28746686
  134.42692603]
 [ 46.67361008  66.03281197  77.97933926 ... 191.22864899 192.91152755
  194.56554603]
 [ 54.61717627  77.97933926  92.26455828 ... 226.88409668 228.88193987
  230.84550178]
 ...
 [132.12818509 191.22864899 226.88409668 ... 560.08706661 565.02302357
  569.8742156 ]
 [133.28746686 192.91152755 228.88193987 ... 565.02302357 570.00248793
  574.89644008]
 [134.42692603 194.56554603 230.84550178 ... 569.8742156  574.89644008
  579.83241789]]


### Task 6: Find the sine,cos and tan-1 value of all elements in the resulting matrix

In [20]:
## BEGIN CODE(1 line of code for each)
import numpy as np
#for sine
np.sin(c)
#for cos
np.cos(c)
#for tan-1
np.tanh(c)
## END CODE

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

# Bonus Task

### Normalizing rows

Normalization is a common technique we use in Machine Learning and Deep Learning is to normalize our data. Here, by normalization we mean changing x to $ \frac{x}{\| x\|} $ (dividing each row vector of x by its norm).

For example, if $$x = 
\begin{bmatrix}
    0 & 3 & 4 \\
    2 & 6 & 4 \\
\end{bmatrix}\tag{1}$$ then $$\| x\| = np.linalg.norm(x, axis = 1, keepdims = True) = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix}\tag{2} $$and        $$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}\tag{3}$$ Note that you can divide matrices of different sizes and it works fine: this is called broadcasting and you're going to learn about it in part 3.


**Exercise**: Implement normalizeRows() to normalize the rows of a matrix . After applying this function to an input matrix x, each row of x should be a vector of unit length (meaning length 1).

In [ ]:
def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    #Begin Here(≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    
    

    # Divide x by its norm.
    
    
    #END CODE

    return x_normf

In [ ]:
x = np.array([
    [0, 5, 7],
    [7, 3, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

**Expected Output**: 

<table style="width:60%">

   <tr> 
       <td> normalizeRows(x) </td> 
       <td> [[0.          0.58123819  0.81373347]
 <br>[0.81373347  0.34874292  0.46499055]</td> 
     </tr>
    
   
</table>

## Create submission file

In [ ]:
## Assign the name of the variable containing the final matrix of Task6 to VARIABLE_NAME variable.

VARIABLE_NAME = 
with open('submission.pickle', 'wb') as p:
    pickle.dump(VARIABLE_NAME, p)